const Links = [
  {
    name: "Word Games",
    items: [
      {
        title: "Boggle eWord",
        description: "eWord Challenge is an online reboot of Boggle word game available in English, Spanish, Filipino and French.",
        link: "https://www.ewordchallenge.net/",
        players: "2+",
        paid: false,
      },
      {
        title: "Snatch",
        description: "The word game to break up any group of friends. No turns, just share link.",
        link: "https://www.playsnatch.io/",
        players: "2+",
        paid: false,
      },
      {
        title: "Scrabble",
        description: "You know Scrabble right? Sign up, send game invites. There’s many options for online scrabble!",
        link: "https://www.isc.ro/",
        players: "2-4",
        paid: false,
      },
      {
        title: "Just One",
        description: "This is an online game based on Just One, a co-op word game.",
        link: "https://oneword.games/",
        players: "3-7",
        paid: false,
      },
      {
        title: "Taboo",
        description: "You can play fantabulous (similar to Taboo) right here. Make up your own rules and keep score right.",
        link: "https://playtaboo.com/",
        players: "2+",
        paid: false,
      },
      {
        title: "Out of Context",
        description: 'Features various "Build the Story" type games (read the rules for each one). Share game code, no sign up involved.',
        link: "https://www.outofcontext.party/",
        players: "2+",
        paid: false,
      },
    ],
  },
  {
    name: "Drawing Games",
    items: [
      {
        title: "Skribbl.io",
        description: "Online Pictionary. Create room, share a link, no sign up involved.",
        link: "https://skribbl.io/",
        players: "2-12",
        paid: false,
      },
      {
        title: "Telestrations",
        description: "The Longest Drawphone Ever. Simplest and best, just share game code. Can adjust timer, can’t draw in colour.",
        link: "https://drawphone.tannerkrewson.com/",
        players: "4+",
        paid: false,
      },
      {
        title: "Fake Artist Goes to New York",
        description: "Fake Artist Online is a drawing game based on Oink Games' tabletop game, A Fake Artist Goes to New York.",
        link: "https://el-artista.herokuapp.com/",
        players: "3-10",
        paid: false,
      },
      {
        title: "Drawing Competition",
        description: "Multiplayer online drawing game. Quickly sign up, then share link. There's a few game modes.",
        link: "https://el-artista.herokuapp.com/",
        players: "2+",
        paid: false,
      },
    ],
  },
  {
    name: "Deduction Games",
    items: [
      {
        title: "Wavelength",
        description: "Longwave is an online, real-time adaptation of the Wavelength board game. Best enjoyed with voice chat!",
        link: "https://longwave.web.app/",
        players: "2+",
        paid: false,
      },
      {
        title: "Codenames",
        description: "A fast paced party game that's sure to keep the whole group entertained, great for families, friends, and total strangers alike.",
        link: "https://codenamesgame.com/",
        players: "4+",
        paid: false,
      },
      {
        title: "Enigma",
        description: "A game based on Decrypto. Just share the room code.",
        link: "https://netgames.io/games/enigma/",
        players: "4-8",
        paid: false,
      },
      {
        title: "Hanabi",
        description: "A place to play Hanab online, a cooperative card game of logic and reasoning. Sign up and join game from lobby. Simply laid out.",
        link: "https://hanab.live/",
        players: "2-5",
        paid: false,
      },
    ],
  },
  {
    name: "Other Games",
    items: [
      {
        title: "Advanced Civilization",
        description: "A web adaptation of the board game Advanced Civilization by Avalon Hill Games. Sign up, then add friends and create a game.",
        link: "http://civ.rol-play.com/",
        players: "2-8",
        paid: false,
      },
      {
        title: "Quiplash",
        description: "Virtually just Quiplash from Jackbox. It’s free, and can have more players than Quiplash. Share room code.",
        link: "https://qwiqwit.com/",
        players: "3-12",
        paid: false,
      },
      {
        title: "Agricola",
        description: "Twenty digitalized games available for free. Join the same game room, don’t have to sign up.",
        link: "http://play-agricola.com/",
        players: "1-5",
        paid: false,
      },
      {
        title: "Railroad Ink",
        description: "A roll and write game where you draw routes on your board trying to connect the exits at its edges. The more you connect, the more points you make!",
        link: "https://ondras.github.io/rri/",
        players: "1+",
        paid: false,
      },
      {
        title: "Risk 'Warzone'",
        description: "If you like Hasbro's RISK® game, you'll love Warzone! Play alone or with friends. Need to sign up. Can customize maps and rules.",
        link: "https://www.warzone.com/",
        players: "2+",
        paid: false,
      },
      {
        title: "Catan",
        description: "Colonist.io is a web game alternative to the top selling board game Settlers of Catan. Create game and share a link.",
        link: "https://colonist.io/",
        players: "3-4",
        paid: false,
      },
      {
        title: "Yahtzee",
        description: "Play the classic Yahtzee for free online, by yourself or with up to 5 friends!",
        link: "https://buddyboardgames.com/yahtzee",
        players: "1-6",
        paid: false,
      },
    ],
  },
  {
    name: "Other",
    items: [
      {
        title: "Jackbox",
        description: "Collections of different party games. The host pays for it. Someone with the game streams. Other players don’t need to sign up or buy anything, instead they simply join the game with their devices.",
        link: "https://jackbox.tv/",
        players: "2-8",
        paid: true,
      },
      {
        title: "Keep Talking and Nobody Explodes",
        description: "Fun co-op game that involves one person describing a bomb and others instructing how to defuse. Only the host with the bomb buys the game. Other players just need the bomb manual.",
        link: "https://keeptalkinggame.com/",
        players: "2+",
        paid: true,
      },
      {
        title: "Town of Salem",
        description: "Similar to Mafia/Werewolf. There’s a bit to understanding with how it runs. Was free, now costs $5-$10 depending on platform (Steam, web, mobile). Classic is free on mobile (limited free goes per day).",
        link: "https://www.blankmediagames.com/",
        players: "2+",
        paid: true,
      },
      {
        title: "Air Console",
        description: "Website with many different knock-off board games and video games. Players join with their phone as a controller, going on the app or the site.",
        link: "https://www.airconsole.com/",
        players: "2+",
        paid: false,
      },
    ],
  },
];

export default Links;
